/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as MentionsRouteImport } from './routes/mentions'
import { Route as LinksRouteImport } from './routes/links'
import { Route as LikesRouteImport } from './routes/likes'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DmsRouteImport } from './routes/dms'
import { Route as DiscussRouteImport } from './routes/discuss'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiStatusRouteImport } from './routes/api/status'
import { Route as ApiSearchDiscussionRouteImport } from './routes/api/search-discussion'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiProfileHydrateRouteImport } from './routes/api/profile-hydrate'
import { Route as ApiPeriodDigestRouteImport } from './routes/api/period-digest'
import { Route as ApiLinkPreviewRouteImport } from './routes/api/link-preview'
import { Route as ApiLinkInsightsRouteImport } from './routes/api/link-insights'
import { Route as ApiInboxRouteImport } from './routes/api/inbox'
import { Route as ApiConversationRouteImport } from './routes/api/conversation'
import { Route as ApiBlocksRouteImport } from './routes/api/blocks'
import { Route as ApiAvatarRouteImport } from './routes/api/avatar'
import { Route as ApiActionRouteImport } from './routes/api/action'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsRoute = MentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const LikesRoute = LikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DmsRoute = DmsRouteImport.update({
  id: '/dms',
  path: '/dms',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussRoute = DiscussRouteImport.update({
  id: '/discuss',
  path: '/discuss',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchDiscussionRoute = ApiSearchDiscussionRouteImport.update({
  id: '/api/search-discussion',
  path: '/api/search-discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileHydrateRoute = ApiProfileHydrateRouteImport.update({
  id: '/api/profile-hydrate',
  path: '/api/profile-hydrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeriodDigestRoute = ApiPeriodDigestRouteImport.update({
  id: '/api/period-digest',
  path: '/api/period-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkPreviewRoute = ApiLinkPreviewRouteImport.update({
  id: '/api/link-preview',
  path: '/api/link-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkInsightsRoute = ApiLinkInsightsRouteImport.update({
  id: '/api/link-insights',
  path: '/api/link-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInboxRoute = ApiInboxRouteImport.update({
  id: '/api/inbox',
  path: '/api/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationRoute = ApiConversationRouteImport.update({
  id: '/api/conversation',
  path: '/api/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlocksRoute = ApiBlocksRouteImport.update({
  id: '/api/blocks',
  path: '/api/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarRoute = ApiAvatarRouteImport.update({
  id: '/api/avatar',
  path: '/api/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionRoute = ApiActionRouteImport.update({
  id: '/api/action',
  path: '/api/action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/discuss': typeof DiscussRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/links': typeof LinksRoute
  '/mentions': typeof MentionsRoute
  '/today': typeof TodayRoute
  '/api/action': typeof ApiActionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/link-insights': typeof ApiLinkInsightsRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/period-digest': typeof ApiPeriodDigestRoute
  '/api/profile-hydrate': typeof ApiProfileHydrateRoute
  '/api/query': typeof ApiQueryRoute
  '/api/search-discussion': typeof ApiSearchDiscussionRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/discuss': typeof DiscussRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/links': typeof LinksRoute
  '/mentions': typeof MentionsRoute
  '/today': typeof TodayRoute
  '/api/action': typeof ApiActionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/link-insights': typeof ApiLinkInsightsRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/period-digest': typeof ApiPeriodDigestRoute
  '/api/profile-hydrate': typeof ApiProfileHydrateRoute
  '/api/query': typeof ApiQueryRoute
  '/api/search-discussion': typeof ApiSearchDiscussionRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRoute
  '/bookmarks': typeof BookmarksRoute
  '/discuss': typeof DiscussRoute
  '/dms': typeof DmsRoute
  '/inbox': typeof InboxRoute
  '/likes': typeof LikesRoute
  '/links': typeof LinksRoute
  '/mentions': typeof MentionsRoute
  '/today': typeof TodayRoute
  '/api/action': typeof ApiActionRoute
  '/api/avatar': typeof ApiAvatarRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/inbox': typeof ApiInboxRoute
  '/api/link-insights': typeof ApiLinkInsightsRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/api/period-digest': typeof ApiPeriodDigestRoute
  '/api/profile-hydrate': typeof ApiProfileHydrateRoute
  '/api/query': typeof ApiQueryRoute
  '/api/search-discussion': typeof ApiSearchDiscussionRoute
  '/api/status': typeof ApiStatusRoute
  '/api/sync': typeof ApiSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/discuss'
    | '/dms'
    | '/inbox'
    | '/likes'
    | '/links'
    | '/mentions'
    | '/today'
    | '/api/action'
    | '/api/avatar'
    | '/api/blocks'
    | '/api/conversation'
    | '/api/inbox'
    | '/api/link-insights'
    | '/api/link-preview'
    | '/api/period-digest'
    | '/api/profile-hydrate'
    | '/api/query'
    | '/api/search-discussion'
    | '/api/status'
    | '/api/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/discuss'
    | '/dms'
    | '/inbox'
    | '/likes'
    | '/links'
    | '/mentions'
    | '/today'
    | '/api/action'
    | '/api/avatar'
    | '/api/blocks'
    | '/api/conversation'
    | '/api/inbox'
    | '/api/link-insights'
    | '/api/link-preview'
    | '/api/period-digest'
    | '/api/profile-hydrate'
    | '/api/query'
    | '/api/search-discussion'
    | '/api/status'
    | '/api/sync'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/bookmarks'
    | '/discuss'
    | '/dms'
    | '/inbox'
    | '/likes'
    | '/links'
    | '/mentions'
    | '/today'
    | '/api/action'
    | '/api/avatar'
    | '/api/blocks'
    | '/api/conversation'
    | '/api/inbox'
    | '/api/link-insights'
    | '/api/link-preview'
    | '/api/period-digest'
    | '/api/profile-hydrate'
    | '/api/query'
    | '/api/search-discussion'
    | '/api/status'
    | '/api/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRoute
  BookmarksRoute: typeof BookmarksRoute
  DiscussRoute: typeof DiscussRoute
  DmsRoute: typeof DmsRoute
  InboxRoute: typeof InboxRoute
  LikesRoute: typeof LikesRoute
  LinksRoute: typeof LinksRoute
  MentionsRoute: typeof MentionsRoute
  TodayRoute: typeof TodayRoute
  ApiActionRoute: typeof ApiActionRoute
  ApiAvatarRoute: typeof ApiAvatarRoute
  ApiBlocksRoute: typeof ApiBlocksRoute
  ApiConversationRoute: typeof ApiConversationRoute
  ApiInboxRoute: typeof ApiInboxRoute
  ApiLinkInsightsRoute: typeof ApiLinkInsightsRoute
  ApiLinkPreviewRoute: typeof ApiLinkPreviewRoute
  ApiPeriodDigestRoute: typeof ApiPeriodDigestRoute
  ApiProfileHydrateRoute: typeof ApiProfileHydrateRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiSearchDiscussionRoute: typeof ApiSearchDiscussionRoute
  ApiStatusRoute: typeof ApiStatusRoute
  ApiSyncRoute: typeof ApiSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions': {
      id: '/mentions'
      path: '/mentions'
      fullPath: '/mentions'
      preLoaderRoute: typeof MentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likes': {
      id: '/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof LikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dms': {
      id: '/dms'
      path: '/dms'
      fullPath: '/dms'
      preLoaderRoute: typeof DmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discuss': {
      id: '/discuss'
      path: '/discuss'
      fullPath: '/discuss'
      preLoaderRoute: typeof DiscussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-discussion': {
      id: '/api/search-discussion'
      path: '/api/search-discussion'
      fullPath: '/api/search-discussion'
      preLoaderRoute: typeof ApiSearchDiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-hydrate': {
      id: '/api/profile-hydrate'
      path: '/api/profile-hydrate'
      fullPath: '/api/profile-hydrate'
      preLoaderRoute: typeof ApiProfileHydrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/period-digest': {
      id: '/api/period-digest'
      path: '/api/period-digest'
      fullPath: '/api/period-digest'
      preLoaderRoute: typeof ApiPeriodDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-preview': {
      id: '/api/link-preview'
      path: '/api/link-preview'
      fullPath: '/api/link-preview'
      preLoaderRoute: typeof ApiLinkPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-insights': {
      id: '/api/link-insights'
      path: '/api/link-insights'
      fullPath: '/api/link-insights'
      preLoaderRoute: typeof ApiLinkInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox': {
      id: '/api/inbox'
      path: '/api/inbox'
      fullPath: '/api/inbox'
      preLoaderRoute: typeof ApiInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation': {
      id: '/api/conversation'
      path: '/api/conversation'
      fullPath: '/api/conversation'
      preLoaderRoute: typeof ApiConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blocks': {
      id: '/api/blocks'
      path: '/api/blocks'
      fullPath: '/api/blocks'
      preLoaderRoute: typeof ApiBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatar': {
      id: '/api/avatar'
      path: '/api/avatar'
      fullPath: '/api/avatar'
      preLoaderRoute: typeof ApiAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/action': {
      id: '/api/action'
      path: '/api/action'
      fullPath: '/api/action'
      preLoaderRoute: typeof ApiActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRoute,
  BookmarksRoute: BookmarksRoute,
  DiscussRoute: DiscussRoute,
  DmsRoute: DmsRoute,
  InboxRoute: InboxRoute,
  LikesRoute: LikesRoute,
  LinksRoute: LinksRoute,
  MentionsRoute: MentionsRoute,
  TodayRoute: TodayRoute,
  ApiActionRoute: ApiActionRoute,
  ApiAvatarRoute: ApiAvatarRoute,
  ApiBlocksRoute: ApiBlocksRoute,
  ApiConversationRoute: ApiConversationRoute,
  ApiInboxRoute: ApiInboxRoute,
  ApiLinkInsightsRoute: ApiLinkInsightsRoute,
  ApiLinkPreviewRoute: ApiLinkPreviewRoute,
  ApiPeriodDigestRoute: ApiPeriodDigestRoute,
  ApiProfileHydrateRoute: ApiProfileHydrateRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiSearchDiscussionRoute: ApiSearchDiscussionRoute,
  ApiStatusRoute: ApiStatusRoute,
  ApiSyncRoute: ApiSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
